name: Updating the resources                # Name of the workflow.

on:                                        # Triggers for the workflow.
  schedule:                                
    - cron: "0 * * * *"                    # Runs hourly (at the start of every hour).
  workflow_dispatch:                       # Allows manual triggering from GitHub UI.

jobs:                                      
  build:                                   
    name: Build and Update Proxies         
    runs-on: windows-latest                # Using the latest Windows runner.

    steps:                                 
      - name: Checkout Repository
        uses: actions/checkout@v4          # Checks out your repository under $GITHUB_WORKSPACE.

      - name: Setup Go
        uses: actions/setup-go@v4          # Sets up Go environment.
        with:
          go-version-file: "go.mod"        # Reads Go version from 'go.mod'.
          cache: true                      # Caches downloaded Go modules.
          check-latest: true               # Always use the latest Go version.
        id: go-setup

      - name: Build and Run Application
        run: |
          go get .                         # Downloads the Go modules.
          go build .                       # Builds your Go application.
          .\proxy-registry.exe -update     # Runs the application with update argument.

      - name: Commit and Push Updates
        run: |
          git config user.name "github-actions"       # Configures GitHub Actions bot as the commit author.
          git config user.email "github-actions@github.com"
          git add .                                    # Adds changes to the staging area.
          git commit -m "Automated update: $(date)"    # Commits changes with a timestamp.
          git pull --rebase origin main                # Rebases with remote main to avoid conflicts.
          git push origin main                         # Pushes the commit to the main branch.
